---
- name: Spinup Instance 
  hosts: localhost
  user: root
  become: yes
  become_method: sudo
  
  roles:
    - instance

- name: Install Tomcat & Deploy files
  hosts: ec2hosts
  gather_facts: True
  user: centos
  become: yes
  become_method: sudo

  vars_files:
    - ./group_vars/variable
         
  roles:
    - firewalld
    - selinux
    - tomcat

